-- =====================================================================
-- 0010  Stat definition catalog  (GENERATED FILE -- DO NOT EDIT BY HAND)
--
-- Regenerate with:  npm run gen:stat-seed
-- Source of truth:  src/lib/stats/catalog.ts
--
-- 173 stats across 7 categories.
-- =====================================================================

insert into public.stat_definitions
  (key, label, category, description, applies_to, value_type, default_points, scorable, sort_order)
values
  ('pass_attempts', 'Pass Attempts', 'Passing', 'Total pass attempts.', 'player', 'count', 0, true, 10),
  ('pass_completions', 'Completions', 'Passing', 'Completed passes.', 'player', 'count', 0, true, 20),
  ('pass_incompletions', 'Incompletions', 'Passing', 'Attempts minus completions.', 'player', 'count', 0, true, 30),
  ('passing_yards', 'Passing Yards', 'Passing', 'Net passing yards.', 'player', 'count', 0.04, true, 40),
  ('passing_tds', 'Passing TDs', 'Passing', 'Touchdown passes thrown.', 'player', 'count', 4, true, 50),
  ('interceptions_thrown', 'Interceptions Thrown', 'Passing', 'Passes intercepted.', 'player', 'count', -2, true, 60),
  ('sacks_taken', 'Sacks Taken', 'Passing', 'Times sacked.', 'player', 'count', 0, true, 70),
  ('sack_yards_lost', 'Sack Yards Lost', 'Passing', 'Yards lost to sacks.', 'player', 'count', 0, true, 80),
  ('passing_first_downs', 'Passing First Downs', 'Passing', 'First downs gained through the air.', 'player', 'count', 0, true, 90),
  ('passing_air_yards', 'Passing Air Yards', 'Passing', 'Total air yards on all attempts.', 'player', 'count', 0, true, 100),
  ('passing_yards_after_catch', 'Passing YAC', 'Passing', 'Yards after catch on completions.', 'player', 'count', 0, true, 110),
  ('pass_2pt_conversions', '2PT Pass Conversions', 'Passing', 'Successful two-point conversion passes.', 'player', 'count', 2, true, 120),
  ('passing_epa', 'Passing EPA', 'Passing', 'Expected points added passing. Can be negative.', 'player', 'count', 0, true, 130),
  ('pass_td_40_plus', 'Pass TDs 40+ Yards', 'Passing', 'Touchdown passes of 40 or more yards.', 'player', 'count', 0, true, 140),
  ('pass_completion_40_plus', 'Completions 40+ Yards', 'Passing', 'Completions of 40 or more yards.', 'player', 'count', 0, true, 150),
  ('pass_completion_20_plus', 'Completions 20+ Yards', 'Passing', 'Completions of 20 or more yards.', 'player', 'count', 0, true, 160),
  ('pass_attempts_deep', 'Deep Attempts', 'Passing', 'Attempts travelling 20+ air yards.', 'player', 'count', 0, true, 170),
  ('pass_completions_deep', 'Deep Completions', 'Passing', 'Completions travelling 20+ air yards.', 'player', 'count', 0, true, 180),
  ('pass_attempts_redzone', 'Red Zone Attempts', 'Passing', 'Pass attempts inside the opponent 20.', 'player', 'count', 0, true, 190),
  ('pass_tds_redzone', 'Red Zone Pass TDs', 'Passing', 'Touchdown passes thrown from inside the 20.', 'player', 'count', 0, true, 200),
  ('pass_300_bonus', '300+ Passing Yards', 'Passing', 'Bonus when a passer clears 300 yards.', 'player', 'flag', 0, true, 210),
  ('pass_400_bonus', '400+ Passing Yards', 'Passing', 'Bonus when a passer clears 400 yards.', 'player', 'flag', 0, true, 220),
  ('pass_500_bonus', '500+ Passing Yards', 'Passing', 'Bonus when a passer clears 500 yards.', 'player', 'flag', 0, true, 230),
  ('pass_4td_bonus', '4+ Passing TDs', 'Passing', 'Bonus for four or more passing touchdowns.', 'player', 'flag', 0, true, 240),
  ('pass_6td_bonus', '6+ Passing TDs', 'Passing', 'Bonus for six or more passing touchdowns.', 'player', 'flag', 0, true, 250),
  ('pass_clean_game', 'No-Interception Game', 'Passing', 'Bonus for 20+ attempts with zero picks.', 'player', 'flag', 0, true, 260),
  ('completion_pct', 'Completion %', 'Passing', 'Completions divided by attempts.', 'player', 'rate', 0, false, 270),
  ('yards_per_attempt', 'Yards / Attempt', 'Passing', 'Passing yards per attempt.', 'player', 'rate', 0, false, 280),
  ('passer_rating', 'Passer Rating', 'Passing', 'Traditional NFL passer rating.', 'player', 'rate', 0, false, 290),
  ('cpoe', 'CPOE', 'Passing', 'Completion percentage over expected.', 'player', 'rate', 0, false, 300),
  ('pacr', 'PACR', 'Passing', 'Passing air conversion ratio.', 'player', 'rate', 0, false, 310),
  ('rush_attempts', 'Rush Attempts', 'Rushing', 'Carries.', 'player', 'count', 0, true, 320),
  ('rushing_yards', 'Rushing Yards', 'Rushing', 'Net rushing yards.', 'player', 'count', 0.1, true, 330),
  ('rushing_tds', 'Rushing TDs', 'Rushing', 'Rushing touchdowns.', 'player', 'count', 6, true, 340),
  ('rushing_first_downs', 'Rushing First Downs', 'Rushing', 'First downs gained on the ground.', 'player', 'count', 0, true, 350),
  ('rushing_epa', 'Rushing EPA', 'Rushing', 'Expected points added rushing. Can be negative.', 'player', 'count', 0, true, 360),
  ('rush_2pt_conversions', '2PT Rush Conversions', 'Rushing', 'Successful two-point conversion runs.', 'player', 'count', 2, true, 370),
  ('rushing_fumbles', 'Rushing Fumbles', 'Rushing', 'Fumbles on rushing plays.', 'player', 'count', 0, true, 380),
  ('rushing_fumbles_lost', 'Rushing Fumbles Lost', 'Rushing', 'Rushing fumbles recovered by the defense.', 'player', 'count', 0, true, 390),
  ('rush_10_plus', 'Rushes 10+ Yards', 'Rushing', 'Carries gaining 10 or more yards.', 'player', 'count', 0, true, 400),
  ('rush_20_plus', 'Rushes 20+ Yards', 'Rushing', 'Carries gaining 20 or more yards.', 'player', 'count', 0, true, 410),
  ('rush_40_plus', 'Rushes 40+ Yards', 'Rushing', 'Carries gaining 40 or more yards.', 'player', 'count', 0, true, 420),
  ('rush_td_40_plus', 'Rush TDs 40+ Yards', 'Rushing', 'Rushing touchdowns of 40 or more yards.', 'player', 'count', 0, true, 430),
  ('rush_attempts_redzone', 'Red Zone Carries', 'Rushing', 'Carries from inside the opponent 20.', 'player', 'count', 0, true, 440),
  ('rush_attempts_inside_5', 'Carries Inside the 5', 'Rushing', 'Carries from inside the opponent 5.', 'player', 'count', 0, true, 450),
  ('rush_yards_before_contact', 'Yards Before Contact', 'Rushing', 'Rushing yards gained before first contact.', 'player', 'count', 0, true, 460),
  ('rush_yards_after_contact', 'Yards After Contact', 'Rushing', 'Rushing yards gained after first contact.', 'player', 'count', 0, true, 470),
  ('rush_broken_tackles', 'Broken Tackles', 'Rushing', 'Tackles broken on rushing plays.', 'player', 'count', 0, true, 480),
  ('rush_stuffed', 'Runs Stuffed', 'Rushing', 'Carries stopped at or behind the line.', 'player', 'count', 0, true, 490),
  ('rush_100_bonus', '100+ Rushing Yards', 'Rushing', 'Bonus when a rusher clears 100 yards.', 'player', 'flag', 0, true, 500),
  ('rush_150_bonus', '150+ Rushing Yards', 'Rushing', 'Bonus when a rusher clears 150 yards.', 'player', 'flag', 0, true, 510),
  ('rush_200_bonus', '200+ Rushing Yards', 'Rushing', 'Bonus when a rusher clears 200 yards.', 'player', 'flag', 0, true, 520),
  ('rush_3td_bonus', '3+ Rushing TDs', 'Rushing', 'Bonus for three or more rushing touchdowns.', 'player', 'flag', 0, true, 530),
  ('yards_per_carry', 'Yards / Carry', 'Rushing', 'Rushing yards per attempt.', 'player', 'rate', 0, false, 540),
  ('rush_yards_over_expected', 'Rush Yards Over Expected', 'Rushing', 'Next Gen Stats RYOE.', 'player', 'count', 0, true, 550),
  ('targets', 'Targets', 'Receiving', 'Times targeted.', 'player', 'count', 0, true, 560),
  ('receptions', 'Receptions', 'Receiving', 'Catches. Set to 1 for full PPR, 0.5 for half.', 'player', 'count', 1, true, 570),
  ('receiving_yards', 'Receiving Yards', 'Receiving', 'Net receiving yards.', 'player', 'count', 0.1, true, 580),
  ('receiving_tds', 'Receiving TDs', 'Receiving', 'Receiving touchdowns.', 'player', 'count', 6, true, 590),
  ('receiving_first_downs', 'Receiving First Downs', 'Receiving', 'First downs gained receiving.', 'player', 'count', 0, true, 600),
  ('receiving_air_yards', 'Receiving Air Yards', 'Receiving', 'Air yards on all targets.', 'player', 'count', 0, true, 610),
  ('receiving_yards_after_catch', 'Receiving YAC', 'Receiving', 'Yards gained after the catch.', 'player', 'count', 0, true, 620),
  ('receiving_epa', 'Receiving EPA', 'Receiving', 'Expected points added receiving. Can be negative.', 'player', 'count', 0, true, 630),
  ('rec_2pt_conversions', '2PT Receptions', 'Receiving', 'Successful two-point conversion catches.', 'player', 'count', 2, true, 640),
  ('receiving_fumbles', 'Receiving Fumbles', 'Receiving', 'Fumbles after a catch.', 'player', 'count', 0, true, 650),
  ('receiving_fumbles_lost', 'Receiving Fumbles Lost', 'Receiving', 'Receiving fumbles lost to the defense.', 'player', 'count', 0, true, 660),
  ('drops', 'Drops', 'Receiving', 'Charted dropped passes.', 'player', 'count', 0, true, 670),
  ('rec_20_plus', 'Receptions 20+ Yards', 'Receiving', 'Catches gaining 20 or more yards.', 'player', 'count', 0, true, 680),
  ('rec_40_plus', 'Receptions 40+ Yards', 'Receiving', 'Catches gaining 40 or more yards.', 'player', 'count', 0, true, 690),
  ('rec_td_40_plus', 'Rec TDs 40+ Yards', 'Receiving', 'Receiving touchdowns of 40 or more yards.', 'player', 'count', 0, true, 700),
  ('targets_redzone', 'Red Zone Targets', 'Receiving', 'Targets inside the opponent 20.', 'player', 'count', 0, true, 710),
  ('targets_endzone', 'End Zone Targets', 'Receiving', 'Targets thrown into the end zone.', 'player', 'count', 0, true, 720),
  ('targets_deep', 'Deep Targets', 'Receiving', 'Targets travelling 20+ air yards.', 'player', 'count', 0, true, 730),
  ('rec_100_bonus', '100+ Receiving Yards', 'Receiving', 'Bonus when a receiver clears 100 yards.', 'player', 'flag', 0, true, 740),
  ('rec_150_bonus', '150+ Receiving Yards', 'Receiving', 'Bonus when a receiver clears 150 yards.', 'player', 'flag', 0, true, 750),
  ('rec_200_bonus', '200+ Receiving Yards', 'Receiving', 'Bonus when a receiver clears 200 yards.', 'player', 'flag', 0, true, 760),
  ('rec_10_catch_bonus', '10+ Receptions', 'Receiving', 'Bonus for ten or more catches.', 'player', 'flag', 0, true, 770),
  ('target_share', 'Target Share', 'Receiving', 'Share of the team''s targets.', 'player', 'rate', 0, false, 780),
  ('air_yards_share', 'Air Yards Share', 'Receiving', 'Share of the team''s air yards.', 'player', 'rate', 0, false, 790),
  ('wopr', 'WOPR', 'Receiving', 'Weighted opportunity rating.', 'player', 'rate', 0, false, 800),
  ('racr', 'RACR', 'Receiving', 'Receiver air conversion ratio.', 'player', 'rate', 0, false, 810),
  ('yards_per_reception', 'Yards / Reception', 'Receiving', 'Receiving yards per catch.', 'player', 'rate', 0, false, 820),
  ('yards_per_target', 'Yards / Target', 'Receiving', 'Receiving yards per target.', 'player', 'rate', 0, false, 830),
  ('fg_made', 'FG Made', 'Kicking', 'Field goals made, any distance.', 'player', 'count', 3, true, 840),
  ('fg_attempts', 'FG Attempts', 'Kicking', 'Field goals attempted.', 'player', 'count', 0, true, 850),
  ('fg_missed', 'FG Missed', 'Kicking', 'Field goals missed.', 'player', 'count', -1, true, 860),
  ('fg_made_0_19', 'FG Made 0-19', 'Kicking', 'Made field goals under 20 yards.', 'player', 'count', 0, true, 870),
  ('fg_made_20_29', 'FG Made 20-29', 'Kicking', 'Made field goals of 20-29 yards.', 'player', 'count', 0, true, 880),
  ('fg_made_30_39', 'FG Made 30-39', 'Kicking', 'Made field goals of 30-39 yards.', 'player', 'count', 0, true, 890),
  ('fg_made_40_49', 'FG Made 40-49', 'Kicking', 'Made field goals of 40-49 yards.', 'player', 'count', 1, true, 900),
  ('fg_made_50_59', 'FG Made 50-59', 'Kicking', 'Made field goals of 50-59 yards.', 'player', 'count', 2, true, 910),
  ('fg_made_60_plus', 'FG Made 60+', 'Kicking', 'Made field goals of 60 or more yards.', 'player', 'count', 3, true, 920),
  ('fg_missed_0_39', 'FG Missed 0-39', 'Kicking', 'Missed field goals under 40 yards.', 'player', 'count', 0, true, 930),
  ('fg_missed_40_49', 'FG Missed 40-49', 'Kicking', 'Missed field goals of 40-49 yards.', 'player', 'count', 0, true, 940),
  ('fg_missed_50_plus', 'FG Missed 50+', 'Kicking', 'Missed field goals of 50 or more yards.', 'player', 'count', 0, true, 950),
  ('fg_made_total_yards', 'FG Yardage', 'Kicking', 'Summed distance of every made field goal.', 'player', 'count', 0, true, 960),
  ('fg_longest', 'Longest FG', 'Kicking', 'Longest made field goal in the game.', 'player', 'count', 0, true, 970),
  ('pat_made', 'XP Made', 'Kicking', 'Extra points made.', 'player', 'count', 1, true, 980),
  ('pat_attempts', 'XP Attempts', 'Kicking', 'Extra points attempted.', 'player', 'count', 0, true, 990),
  ('pat_missed', 'XP Missed', 'Kicking', 'Extra points missed.', 'player', 'count', -1, true, 1000),
  ('fumbles', 'Fumbles', 'Fumbles & Returns', 'All fumbles, lost or not.', 'player', 'count', 0, true, 1010),
  ('fumbles_lost', 'Fumbles Lost', 'Fumbles & Returns', 'Fumbles recovered by the opponent.', 'player', 'count', -2, true, 1020),
  ('fumble_recoveries_own', 'Own Fumble Recoveries', 'Fumbles & Returns', 'Own fumbles recovered by the player.', 'player', 'count', 0, true, 1030),
  ('fumble_recovery_tds', 'Fumble Recovery TDs', 'Fumbles & Returns', 'Touchdowns scored on a fumble recovery.', 'player', 'count', 6, true, 1040),
  ('kick_returns', 'Kick Returns', 'Fumbles & Returns', 'Kickoff returns.', 'player', 'count', 0, true, 1050),
  ('kick_return_yards', 'Kick Return Yards', 'Fumbles & Returns', 'Yards on kickoff returns.', 'player', 'count', 0, true, 1060),
  ('kick_return_tds', 'Kick Return TDs', 'Fumbles & Returns', 'Kickoff returns for a touchdown.', 'player', 'count', 6, true, 1070),
  ('punt_returns', 'Punt Returns', 'Fumbles & Returns', 'Punt returns.', 'player', 'count', 0, true, 1080),
  ('punt_return_yards', 'Punt Return Yards', 'Fumbles & Returns', 'Yards on punt returns.', 'player', 'count', 0, true, 1090),
  ('punt_return_tds', 'Punt Return TDs', 'Fumbles & Returns', 'Punt returns for a touchdown.', 'player', 'count', 6, true, 1100),
  ('offensive_snaps', 'Offensive Snaps', 'Fumbles & Returns', 'Snaps played on offense.', 'player', 'count', 0, true, 1110),
  ('snap_share', 'Snap Share', 'Fumbles & Returns', 'Share of the team''s offensive snaps.', 'player', 'rate', 0, false, 1120),
  ('total_touches', 'Touches', 'Fumbles & Returns', 'Carries plus receptions.', 'player', 'count', 0, true, 1130),
  ('total_yards_from_scrimmage', 'Yards From Scrimmage', 'Fumbles & Returns', 'Rushing plus receiving yards.', 'player', 'count', 0, true, 1140),
  ('all_purpose_yards', 'All-Purpose Yards', 'Fumbles & Returns', 'Scrimmage yards plus return yards.', 'player', 'count', 0, true, 1150),
  ('total_tds', 'Total TDs', 'Fumbles & Returns', 'Every touchdown scored, any method.', 'player', 'count', 0, true, 1160),
  ('tackles_solo', 'Solo Tackles', 'Defense (IDP)', 'Unassisted tackles.', 'player', 'count', 0, true, 1170),
  ('tackles_assist', 'Assisted Tackles', 'Defense (IDP)', 'Assists on a tackle.', 'player', 'count', 0, true, 1180),
  ('tackles_combined', 'Combined Tackles', 'Defense (IDP)', 'Solo plus assisted tackles.', 'player', 'count', 0, true, 1190),
  ('tackles_for_loss', 'Tackles For Loss', 'Defense (IDP)', 'Tackles behind the line of scrimmage.', 'player', 'count', 0, true, 1200),
  ('def_sacks', 'Sacks', 'Defense (IDP)', 'Sacks recorded. Halves are possible.', 'player', 'count', 0, true, 1210),
  ('def_sack_yards', 'Sack Yards', 'Defense (IDP)', 'Yards lost on the sacks recorded.', 'player', 'count', 0, true, 1220),
  ('qb_hits', 'QB Hits', 'Defense (IDP)', 'Hits on the quarterback.', 'player', 'count', 0, true, 1230),
  ('def_interceptions', 'Interceptions', 'Defense (IDP)', 'Passes intercepted.', 'player', 'count', 0, true, 1240),
  ('def_interception_yards', 'INT Return Yards', 'Defense (IDP)', 'Return yards on interceptions.', 'player', 'count', 0, true, 1250),
  ('def_interception_tds', 'Pick Sixes', 'Defense (IDP)', 'Interceptions returned for a touchdown.', 'player', 'count', 0, true, 1260),
  ('passes_defended', 'Passes Defended', 'Defense (IDP)', 'Passes broken up.', 'player', 'count', 0, true, 1270),
  ('forced_fumbles', 'Forced Fumbles', 'Defense (IDP)', 'Fumbles forced.', 'player', 'count', 0, true, 1280),
  ('def_fumble_recoveries', 'Fumble Recoveries', 'Defense (IDP)', 'Opponent fumbles recovered.', 'player', 'count', 0, true, 1290),
  ('def_fumble_return_yards', 'Fumble Return Yards', 'Defense (IDP)', 'Return yards on recovered fumbles.', 'player', 'count', 0, true, 1300),
  ('def_fumble_tds', 'Fumble Return TDs', 'Defense (IDP)', 'Recovered fumbles returned for a score.', 'player', 'count', 0, true, 1310),
  ('def_safeties', 'Safeties', 'Defense (IDP)', 'Safeties recorded.', 'player', 'count', 0, true, 1320),
  ('def_blocked_kicks', 'Blocked Kicks', 'Defense (IDP)', 'Field goals, punts or XPs blocked.', 'player', 'count', 0, true, 1330),
  ('def_tds', 'Defensive TDs', 'Defense (IDP)', 'Any touchdown scored by the defender.', 'player', 'count', 0, true, 1340),
  ('defensive_snaps', 'Defensive Snaps', 'Defense (IDP)', 'Snaps played on defense.', 'player', 'count', 0, true, 1350),
  ('def_stuffs', 'Run Stuffs', 'Defense (IDP)', 'Ball carriers stopped at or behind the line.', 'player', 'count', 0, true, 1360),
  ('def_targets', 'Targets Allowed', 'Defense (IDP)', 'Times targeted in coverage.', 'player', 'count', 0, true, 1370),
  ('def_completions_allowed', 'Completions Allowed', 'Defense (IDP)', 'Catches allowed in coverage.', 'player', 'count', 0, true, 1380),
  ('def_yards_allowed', 'Coverage Yards Allowed', 'Defense (IDP)', 'Receiving yards allowed in coverage.', 'player', 'count', 0, true, 1390),
  ('dst_sacks', 'Sacks', 'Team Defense / ST', 'Team sacks.', 'team_defense', 'count', 1, true, 1400),
  ('dst_interceptions', 'Interceptions', 'Team Defense / ST', 'Team interceptions.', 'team_defense', 'count', 2, true, 1410),
  ('dst_fumble_recoveries', 'Fumble Recoveries', 'Team Defense / ST', 'Opponent fumbles recovered.', 'team_defense', 'count', 2, true, 1420),
  ('dst_forced_fumbles', 'Forced Fumbles', 'Team Defense / ST', 'Fumbles forced by the defense.', 'team_defense', 'count', 0, true, 1430),
  ('dst_safeties', 'Safeties', 'Team Defense / ST', 'Safeties scored.', 'team_defense', 'count', 2, true, 1440),
  ('dst_tds', 'Defensive/ST TDs', 'Team Defense / ST', 'Any defensive or special teams touchdown.', 'team_defense', 'count', 6, true, 1450),
  ('dst_blocked_kicks', 'Blocked Kicks', 'Team Defense / ST', 'Kicks blocked.', 'team_defense', 'count', 2, true, 1460),
  ('dst_tackles_for_loss', 'Tackles For Loss', 'Team Defense / ST', 'Team tackles behind the line.', 'team_defense', 'count', 0, true, 1470),
  ('dst_qb_hits', 'QB Hits', 'Team Defense / ST', 'Team hits on the quarterback.', 'team_defense', 'count', 0, true, 1480),
  ('dst_passes_defended', 'Passes Defended', 'Team Defense / ST', 'Team passes broken up.', 'team_defense', 'count', 0, true, 1490),
  ('dst_return_yards', 'Return Yards', 'Team Defense / ST', 'Kick plus punt return yards.', 'team_defense', 'count', 0, true, 1500),
  ('dst_return_tds', 'Return TDs', 'Team Defense / ST', 'Kick or punt returns for a touchdown.', 'team_defense', 'count', 0, true, 1510),
  ('dst_points_allowed', 'Points Allowed', 'Team Defense / ST', 'Points surrendered. Score this negatively.', 'team_defense', 'count', 0, true, 1520),
  ('dst_yards_allowed', 'Yards Allowed', 'Team Defense / ST', 'Total yards surrendered.', 'team_defense', 'count', 0, true, 1530),
  ('dst_pass_yards_allowed', 'Pass Yards Allowed', 'Team Defense / ST', 'Passing yards surrendered.', 'team_defense', 'count', 0, true, 1540),
  ('dst_rush_yards_allowed', 'Rush Yards Allowed', 'Team Defense / ST', 'Rushing yards surrendered.', 'team_defense', 'count', 0, true, 1550),
  ('dst_first_downs_allowed', 'First Downs Allowed', 'Team Defense / ST', 'First downs surrendered.', 'team_defense', 'count', 0, true, 1560),
  ('dst_three_and_outs', 'Three And Outs', 'Team Defense / ST', 'Opponent drives ending in a punt after three plays.', 'team_defense', 'count', 0, true, 1570),
  ('dst_fourth_down_stops', 'Fourth Down Stops', 'Team Defense / ST', 'Opponent fourth down attempts stopped.', 'team_defense', 'count', 0, true, 1580),
  ('dst_turnovers', 'Total Turnovers', 'Team Defense / ST', 'Interceptions plus fumble recoveries.', 'team_defense', 'count', 0, true, 1590),
  ('dst_shutout', 'Shutout', 'Team Defense / ST', 'Opponent held to zero points.', 'team_defense', 'flag', 0, true, 1600),
  ('dst_pa_0', 'Points Allowed: 0', 'Team Defense / ST', 'Bonus tier when the opponent is shut out.', 'team_defense', 'flag', 10, true, 1610),
  ('dst_pa_1_6', 'Points Allowed: 1-6', 'Team Defense / ST', 'Bonus tier for 1-6 points allowed.', 'team_defense', 'flag', 7, true, 1620),
  ('dst_pa_7_13', 'Points Allowed: 7-13', 'Team Defense / ST', 'Bonus tier for 7-13 points allowed.', 'team_defense', 'flag', 4, true, 1630),
  ('dst_pa_14_20', 'Points Allowed: 14-20', 'Team Defense / ST', 'Bonus tier for 14-20 points allowed.', 'team_defense', 'flag', 1, true, 1640),
  ('dst_pa_21_27', 'Points Allowed: 21-27', 'Team Defense / ST', 'Bonus tier for 21-27 points allowed.', 'team_defense', 'flag', 0, true, 1650),
  ('dst_pa_28_34', 'Points Allowed: 28-34', 'Team Defense / ST', 'Bonus tier for 28-34 points allowed.', 'team_defense', 'flag', -1, true, 1660),
  ('dst_pa_35_plus', 'Points Allowed: 35+', 'Team Defense / ST', 'Bonus tier for 35 or more points allowed.', 'team_defense', 'flag', -4, true, 1670),
  ('dst_ya_under_100', 'Yards Allowed: <100', 'Team Defense / ST', 'Bonus tier for under 100 total yards allowed.', 'team_defense', 'flag', 0, true, 1680),
  ('dst_ya_100_199', 'Yards Allowed: 100-199', 'Team Defense / ST', 'Bonus tier for 100-199 yards allowed.', 'team_defense', 'flag', 0, true, 1690),
  ('dst_ya_200_299', 'Yards Allowed: 200-299', 'Team Defense / ST', 'Bonus tier for 200-299 yards allowed.', 'team_defense', 'flag', 0, true, 1700),
  ('dst_ya_300_399', 'Yards Allowed: 300-399', 'Team Defense / ST', 'Bonus tier for 300-399 yards allowed.', 'team_defense', 'flag', 0, true, 1710),
  ('dst_ya_400_449', 'Yards Allowed: 400-449', 'Team Defense / ST', 'Bonus tier for 400-449 yards allowed.', 'team_defense', 'flag', 0, true, 1720),
  ('dst_ya_450_plus', 'Yards Allowed: 450+', 'Team Defense / ST', 'Bonus tier for 450 or more yards allowed.', 'team_defense', 'flag', 0, true, 1730)
on conflict (key) do update set
  label          = excluded.label,
  category       = excluded.category,
  description    = excluded.description,
  applies_to     = excluded.applies_to,
  value_type     = excluded.value_type,
  default_points = excluded.default_points,
  scorable       = excluded.scorable,
  sort_order     = excluded.sort_order;

-- Remove stats that have been dropped from the catalog.
delete from public.stat_definitions
where key not in ('pass_attempts', 'pass_completions', 'pass_incompletions', 'passing_yards', 'passing_tds', 'interceptions_thrown', 'sacks_taken', 'sack_yards_lost', 'passing_first_downs', 'passing_air_yards', 'passing_yards_after_catch', 'pass_2pt_conversions', 'passing_epa', 'pass_td_40_plus', 'pass_completion_40_plus', 'pass_completion_20_plus', 'pass_attempts_deep', 'pass_completions_deep', 'pass_attempts_redzone', 'pass_tds_redzone', 'pass_300_bonus', 'pass_400_bonus', 'pass_500_bonus', 'pass_4td_bonus', 'pass_6td_bonus', 'pass_clean_game', 'completion_pct', 'yards_per_attempt', 'passer_rating', 'cpoe', 'pacr', 'rush_attempts', 'rushing_yards', 'rushing_tds', 'rushing_first_downs', 'rushing_epa', 'rush_2pt_conversions', 'rushing_fumbles', 'rushing_fumbles_lost', 'rush_10_plus', 'rush_20_plus', 'rush_40_plus', 'rush_td_40_plus', 'rush_attempts_redzone', 'rush_attempts_inside_5', 'rush_yards_before_contact', 'rush_yards_after_contact', 'rush_broken_tackles', 'rush_stuffed', 'rush_100_bonus', 'rush_150_bonus', 'rush_200_bonus', 'rush_3td_bonus', 'yards_per_carry', 'rush_yards_over_expected', 'targets', 'receptions', 'receiving_yards', 'receiving_tds', 'receiving_first_downs', 'receiving_air_yards', 'receiving_yards_after_catch', 'receiving_epa', 'rec_2pt_conversions', 'receiving_fumbles', 'receiving_fumbles_lost', 'drops', 'rec_20_plus', 'rec_40_plus', 'rec_td_40_plus', 'targets_redzone', 'targets_endzone', 'targets_deep', 'rec_100_bonus', 'rec_150_bonus', 'rec_200_bonus', 'rec_10_catch_bonus', 'target_share', 'air_yards_share', 'wopr', 'racr', 'yards_per_reception', 'yards_per_target', 'fg_made', 'fg_attempts', 'fg_missed', 'fg_made_0_19', 'fg_made_20_29', 'fg_made_30_39', 'fg_made_40_49', 'fg_made_50_59', 'fg_made_60_plus', 'fg_missed_0_39', 'fg_missed_40_49', 'fg_missed_50_plus', 'fg_made_total_yards', 'fg_longest', 'pat_made', 'pat_attempts', 'pat_missed', 'fumbles', 'fumbles_lost', 'fumble_recoveries_own', 'fumble_recovery_tds', 'kick_returns', 'kick_return_yards', 'kick_return_tds', 'punt_returns', 'punt_return_yards', 'punt_return_tds', 'offensive_snaps', 'snap_share', 'total_touches', 'total_yards_from_scrimmage', 'all_purpose_yards', 'total_tds', 'tackles_solo', 'tackles_assist', 'tackles_combined', 'tackles_for_loss', 'def_sacks', 'def_sack_yards', 'qb_hits', 'def_interceptions', 'def_interception_yards', 'def_interception_tds', 'passes_defended', 'forced_fumbles', 'def_fumble_recoveries', 'def_fumble_return_yards', 'def_fumble_tds', 'def_safeties', 'def_blocked_kicks', 'def_tds', 'defensive_snaps', 'def_stuffs', 'def_targets', 'def_completions_allowed', 'def_yards_allowed', 'dst_sacks', 'dst_interceptions', 'dst_fumble_recoveries', 'dst_forced_fumbles', 'dst_safeties', 'dst_tds', 'dst_blocked_kicks', 'dst_tackles_for_loss', 'dst_qb_hits', 'dst_passes_defended', 'dst_return_yards', 'dst_return_tds', 'dst_points_allowed', 'dst_yards_allowed', 'dst_pass_yards_allowed', 'dst_rush_yards_allowed', 'dst_first_downs_allowed', 'dst_three_and_outs', 'dst_fourth_down_stops', 'dst_turnovers', 'dst_shutout', 'dst_pa_0', 'dst_pa_1_6', 'dst_pa_7_13', 'dst_pa_14_20', 'dst_pa_21_27', 'dst_pa_28_34', 'dst_pa_35_plus', 'dst_ya_under_100', 'dst_ya_100_199', 'dst_ya_200_299', 'dst_ya_300_399', 'dst_ya_400_449', 'dst_ya_450_plus');
